### ISSUE TITLE
Model saving is failed because Save function could not create the full path if it doesn't exist

### ISSUE THREAD

**Issue by zaleslaw** [Kotlin/kotlindl#525]
We have a model that should be saved on the disk.
But after calling the save method, the following exception is thrown, which is not expected.

`private const val PATH_TO_MODEL = "savedmodels/customResNet50"`

```kotlin
        it.save(
            File(PATH_TO_MODEL),
            SavingFormat.JSON_CONFIG_CUSTOM_VARIABLES,
            writingMode = WritingMode.OVERRIDE
        )
```

`Exception in thread "main" java.io.FileNotFoundException: C:\.....\savedmodels\customResNet50\modelConfig.json (The system cannot find the path specified)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:134)
	at org.jetbrains.kotlinx.dl.api.inference.keras.ModelSaverKt.saveModelConfiguration(ModelSaver.kt:43)
	at org.jetbrains.kotlinx.dl.api.core.Functional.saveModel(Functional.kt:320)
	at org.jetbrains.kotlinx.dl.api.core.Functional.saveModel$default(Functional.kt:318)
	at org.jetbrains.kotlinx.dl.api.core.Functional.saveInKerasFormat(Functional.kt:314)
	at org.jetbrains.kotlinx.dl.api.core.Functional.save(Functional.kt:309)
	at org.jetbrains.kotlinx.dl.api.core.TrainableModel.save$default(TrainableModel.kt:386)
	at cnn.TransferLearningExportImportKt.main(transferLearningExportImport.kt:104)
	at cnn.TransferLearningExportImportKt.main(transferLearningExportImport.kt)`

P.S. It was fixed when I created the folder `savedmodels` manually

**Comment by zaleslaw** [comment]
Closed in #534
